### ISSUE TITLE
Validate Signature of download files

### ISSUE THREAD

**Issue by pquerna** [ashokgelal/Magpie#19]
Thanks for making Magpie, it looks great.

When downloading an update, it doesn't look like Magpie currently validates the file in any way.  (i couldn't find it if it does)

It would be great if Magpie would validate signatures based on a Public Key.  Traditionally Appcasts / Sparkle have used DSA signatures, but it would be very reasonable to use a RSA w/ SHA256 as a more modern approach.

**Comment by ashokgelal** [comment]
Yes, we'll definitely add signature validation feature added before we release version 1.0. We've not decided which one but there will be one. I've added updated README file to include it as a TODO item.

**Comment by ashokgelal** [comment]
FYI: https://github.com/ashokgelal/Magpie-SignatureGenerator
We already have a working version of Magpie that performs signature verification and will be pushed soon.

**Comment by ashokgelal** [comment]
This is now been resolved: https://github.com/ashokgelal/Magpie#signing-updates
